### ISSUE TITLE
Because rust and cargo need to be installed in advance, there will be some extra work, it is recommended to install the rust and cargo in the loader when npm install, to reduce the cognitive cost

### ISSUE THREAD

**Issue by baiyuze** [yeskiy/rustwasm-loader#7]
Because rust and cargo need to be installed in advance, there will be some extra work, it is recommended to install the rust and cargo in the loader when npm install, to reduce the cognitive cost

**Comment by yeskiy** [comment]
Hey! 

The actual `rust` environment actually depends from machine to machine, so after a dozen of internal testing, I decided to not include an automatic `rust` install when loader is installed/downloaded.

I did an update of [README](https://github.com/yeskiy/rustwasm-loader/blob/main/README.md) though, it should be much clearer, what should be installed on.

If you guys have other opinions about this issue, feel free to re-open!
